services:
  postgres:
    image: postgres:13.4
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=muse
      - POSTGRES_PASSWORD=muse
      - POSTGRES_DB=muse
      - APP_DB_USER=muse
      - APP_DB_PASS=muse
      - APP_DB_NAME=muse
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
